### ISSUE TITLE
Latest version fails testing

### ISSUE THREAD

**Issue by daliwali** [ashi009/node-fast-crc32c#9]
Hi,

Upgrading from `1.0.2` to `1.0.3` caused tests to fail. I looked at the commits and it seems Node 4 support was dropped in a patch version (!)

It seems to fail without having a fallback option.

```
Error: Failed to find available CRC-32C implementation.
    at /home/travis/build/fortunejs/fortune/node_modules/fast-crc32c/loader.js:20:7
    at Object.<anonymous> (/home/travis/build/fortunejs/fortune/node_modules/fast-crc32c/loader.js:22:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/fortunejs/fortune/lib/net/http_server.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/fortunejs/fortune/lib/index.js:15:12)
```

**Comment by ashi009** [comment]
I thought npm will automatically resolve the latest supported version.  Sorry for that, let me fix it.

**Comment by ashi009** [comment]
Rolling out v1.0.4 to revert the change. Please update to the latest version.

**Comment by ashi009** [comment]
#17 has addressed this.
